language: python

jobs:
  include:
    - python: 3.8
    - python: 3.7


install:
   - pip install 'anyio[curio,trio] ~= 2.0'
   - pip install overly
   - pip install "pytest >= 3.7.2"
   - pip install -e .

script:
  - pytest tests --verbose --tb=native
  # - pylint asks tests
  # temp disable until bugfix for
  # AttributeError: 'FunctionDef' object has no attribute 'ancestors'

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#8banana"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
